FROM nginx:alpine

RUN apk --no-cache add ca-certificates unzip sed p7zip xz wget bash npm
RUN npm install -g coffee-script

ARG RETROARCH_TYPE=stable
ARG RETROARCH_VERSION=1.16.0
ENV ROOT_WWW_PATH /usr/share/nginx/html

# bash as default
SHELL ["/bin/bash", "-c"]

ADD fn.sh /
RUN source fn.sh \
&& install_retroarch_web ${RETROARCH_TYPE} ${RETROARCH_VERSION} ${ROOT_WWW_PATH}

WORKDIR ${ROOT_WWW_PATH}

EXPOSE 80

COPY entrypoint.sh /

CMD [ "sh", "/entrypoint.sh"]
