name: Deploy
on:
 workflow_dispatch:
    inputs:
      retroarchtype:
        default: "stable"
        description: "stable or nightly"
      retroarchversion:
        default: "1.15.0"
        description: "version"

jobs:
  deployment:
    name: Deploy - ${{ github.event.inputs.retroarchtype }} v${{ github.event.inputs.retroarchversion }}
    runs-on: ubuntu-latest
    environment: DockerHub
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & Push
        run: |
          env
          make push \
            RETROARCH_TYPE=${{ github.event.inputs.retroarchtype }} \
            RETROARCH_VERSION=${{ github.event.inputs.retroarchversion }}
